# Generated by Django 4.1.7 on 2023-04-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrashCan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycle_type', models.CharField(max_length=20)),
                ('garbage_capacity', models.FloatField()),
                ('recycle_capacity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.CharField(max_length=20)),
                ('garbage_weight', models.FloatField()),
                ('recycle_weight', models.FloatField()),
                ('coin', models.FloatField()),
            ],
        ),
    ]
