# Generated by Django 4.1.7 on 2023-04-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='position',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='situation',
            field=models.CharField(default='', max_length=20),
        ),
    ]
