# Generated by Django 4.1.7 on 2023-04-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_trashcan_position_trashcan_situation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashcan',
            old_name='garbage_capacity',
            new_name='cap_recy',
        ),
        migrations.RenameField(
            model_name='trashcan',
            old_name='recycle_capacity',
            new_name='cap_trash',
        ),
        migrations.RenameField(
            model_name='trashcan',
            old_name='situation',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='garbage_weight',
            new_name='weight_recy',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='recycle_weight',
            new_name='weight_trash',
        ),
        migrations.RemoveField(
            model_name='trashcan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_account',
        ),
        migrations.AddField(
            model_name='trashcan',
            name='can_id',
            field=models.CharField(default='aaa', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='aaa', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
