# Generated by Django 4.1.7 on 2023-04-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todowork',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
